### ISSUE TITLE
Три замечания

### ISSUE THREAD

**Issue by KolosovKD** [avalon-dev-j110/laboratornaya-rabota-no3-kksenoss#1]
1. Создайте для исправления новую ветку гит, вней внесите изменения, запуште эту новую ветку на гитхаб и сделайте пул реквест.
1. В классе RandomInitializer не выполнено условие:
- Диапазон, в пределах которого будут получены случайные значения, передаётся в конструктор класса при инициализации.
1. В класса FibonacciInitializer в строке 32 будет исключение, если передать массив длиной 1 элемент.

**Comment by kksenoss** [comment]
замечания исправлены
